export default [
  {
    Title: 'Superman Returns',
    Year: '2006',
    Rated: 'PG-13',
    Released: '30 Jun 2006',
    Runtime: '154 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Bryan Singer',
    Writer: 'Michael Dougherty, Dan Harris, Bryan Singer',
    Actors: 'Brandon Routh, Kevin Spacey, Kate Bosworth',
    Plot: 'Superman returns to Earth after spending five years in space examining his homeworld Krypton. But he finds things have changed while he was gone, and he must once again prove himself important to the world.',
    Language: 'English, German, French',
    Country: 'United States, Australia',
    Awards: 'Nominated for 1 Oscar. 12 wins & 47 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjg1ZGRiMTEtYmU4Zi00NTkwLWJmODQtMjU3MTAyMGQ2OGZlXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      {Source: 'Internet Movie Database', Value: '6.1/10'},
      {Source: 'Rotten Tomatoes', Value: '74%'},
      {Source: 'Metacritic', Value: '72/100'},
    ],
    Metascore: '72',
    imdbRating: '6.1',
    imdbVotes: '294,943',
    imdbID: 'tt0348150',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$200,081,192',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Batman',
    Year: '2022',
    Rated: 'PG-13',
    Released: '04 Mar 2022',
    Runtime: '176 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Matt Reeves',
    Writer: 'Matt Reeves, Peter Craig, Bob Kane',
    Actors: 'Robert Pattinson, Zoë Kravitz, Jeffrey Wright',
    Plot: "When a sadistic serial killer begins murdering key political figures in Gotham, the Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    Language: 'English, Spanish, Latin, Italian',
    Country: 'United States',
    Awards: 'Nominated for 3 Oscars. 39 wins & 185 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMmU5NGJlMzAtMGNmOC00YjJjLTgyMzUtNjAyYmE4Njg5YWMyXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      {Source: 'Internet Movie Database', Value: '7.8/10'},
      {Source: 'Rotten Tomatoes', Value: '85%'},
      {Source: 'Metacritic', Value: '72/100'},
    ],
    Metascore: '72',
    imdbRating: '7.8',
    imdbVotes: '855,531',
    imdbID: 'tt1877830',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$369,345,583',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];
